#!/usr/bin/env node
// gourcify-main.mjs — turns the "galaxy" of the earlier mission-control board (project/Main.dc.html) into the
// Gource-style workspace scene of the Agentspace core: the 3D canvas is replaced by the viewer's two canvases,
// the core and the three team runs (demo/runs: medytacja, panel, niemcy) are inlined, and draw() drives the
// viewer from the board's own clock and scenario picker. Panels, timeline and report stay as they were.
// Idempotent: a second run replaces the previously inlined core.
//   node artifact/gourcify-main.mjs [repo root]
import fs from 'node:fs';
import path from 'node:path';
import { coreBundle, runsScript } from './bundle-core.mjs';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const REPO = process.argv[2] || path.resolve(HERE, '..');
const FILE = path.join(HERE, 'project', 'Main.dc.html');
let s = fs.readFileSync(FILE, 'utf8');
const must = (cond, what) => { if (!cond) throw new Error('Main.dc.html: ' + what); };

// 1. canvases: the viewer's WebGL canvas and its overlay (text, picking, pan / zoom) instead of the 3D canvas
const CANVAS = '<canvas id="hm-gl" aria-hidden="true" style="position: absolute; left: 0; top: 0; width: 100%; height: 100%; display: block"></canvas>\n'
  + '<canvas id="hm-ov" role="img" aria-label="Przestrzeń robocza zespołu jak w Gource: przeciągnij, aby przesunąć, kółkiem przybliż, kliknij agenta, aby zobaczyć, co robił" style="position: absolute; left: 0; top: 0; width: 100%; height: 100%; display: block; touch-action: none; cursor: grab"></canvas>';
if (/<canvas id="hm-cv"[^>]*><\/canvas>/.test(s)) s = s.replace(/<canvas id="hm-cv"[^>]*><\/canvas>/, CANVAS);
must(s.includes('id="hm-gl"') && s.includes('id="hm-ov"'), 'canvas not found');

// 2. the HUD chip names what the scene now shows
s = s.replace('<span style="color: #F2C14E">◆ Przestrzeń neuronowa</span>', '<span style="color: #F2C14E">◆ Przestrzeń robocza · jak Gource</span>');
s = s.replace('każdy agent krąży po swojej orbicie · impulsy to wiadomości · złoto to Hermes', 'drzewo to pliki zespołu · awatary to agenci · promienie: zielony tworzy, pomarańczowy zmienia, niebieski czyta');

// 2b. galaxy wording in the HUD, and the camera buttons drive the new scene
const swap = [
  ["{ label: 'agenci w orbicie',", "{ label: 'agenci w zespole',"],
  ["{ label: 'impulsy w locie',", "{ label: 'wiadomości w locie',"],
  ["{ label: 'synapsy', value: String(synapses), color: '#D6BEFF' },\n", ''],
  ['<span>synapsy <span style="color: #E8ECF8">{{synCount}}</span></span>\n', ''],
  ['aria-label="Automatyczny obrót kamery"', 'aria-label="Pokaż całe drzewo"'],

  ["      zoomIn: () => { this._cam.zoomT = clamp(this._cam.zoomT * 1.2, 0.6, 1.8); },", "      zoomIn: () => { if (this._nw) this._nw.zoom(1.2); },"],
  ["      zoomOut: () => { this._cam.zoomT = clamp(this._cam.zoomT / 1.2, 0.6, 1.8); },", "      zoomOut: () => { if (this._nw) this._nw.zoom(1 / 1.2); },"],
  ["      resetCam: () => { const c = this._cam; c.dyaw = 0; c.dpitch = 0; c.zoomT = 1; this.setState({ sel: 'hermes' }); },", "      resetCam: () => { if (this._nw) this._nw.reset(); this.setState({ sel: 'hermes' }); },"],
  ["      toggleOrbit: () => { this._orbit = !this._orbit; this.setState({ orbit: this._orbit }); },", "      toggleOrbit: () => { if (this._nw) this._nw.reset(); },"],
];
for (const [x, y] of swap) s = s.split(x).join(y);
s = s.replace(/(onClick="\{\{setView3d\}\}"[^>]*>)3D<\/button>/, '$1Gource</button>');

// 3. the core and the team runs, between markers, at the top of the board script
const BEGIN = '// @@NW-BEGIN (generated by artifact/gourcify-main.mjs from packages/core and demo/runs)';
const END = '// @@NW-END';
const block = BEGIN + '\n' + coreBundle(REPO) + '\n' + runsScript(REPO, [['medytacja', 'Premiera aplikacji'], ['panel', 'Panel sprzedaży'], ['niemcy', 'Wejście do Niemiec']]) + '\n' + END + '\n';
if (s.includes(BEGIN)) s = s.slice(0, s.indexOf(BEGIN)) + block + s.slice(s.indexOf(END) + END.length + 1);
else {
  const anchor = '<script type="text/x-dc" data-dc-script data-props=\'{"$preview":{"width":1440,"height":1760}}\'>\n';
  must(s.includes(anchor), 'board script not found');
  s = s.replace(anchor, anchor + block);
}

// 4. draw(): the viewer follows this board's clock and scenario, framed between the board's panels
const DRAW = `  draw() {
    if (typeof document === 'undefined' || typeof document.getElementById !== 'function' || document.hidden) return;
    const gl = document.getElementById('hm-gl');
    const ov = document.getElementById('hm-ov');
    if (!gl || !ov) return;
    if (!this._nw || this._nwCv !== gl) {
      if (this._nw && this._nw.destroy) this._nw.destroy();
      this._nw = NW.createViewer({ gl, overlay: ov, studio: false, focus: false, autoRotate: false, caption: false, date: false });
      this._nwCv = gl;
      this._nwSid = null;
      this._nwN = 0;
      // clicking an avatar selects that agent in the board's own panels
      this._nw.onSelect = (id) => {
        if (!id || id.slice(0, 5) !== 'user:') return;
        const a = id.slice(5);
        const known = a === 'hermes' || (this.scen().agents || []).some((x) => x.id === a);
        if (known) this.setState({ sel: a });
      };
    }
    const v = this._nw;
    if (this._nwSid !== this.state.sid) {
      const run = NW_RUNS.find((r) => r.id === this.state.sid);
      if (run) v.setTimeline(NW.createTimeline(NW.parseJsonl(run.jsonl).events));
      this._nwSid = this.state.sid;
    }
    v.pause();
    v.setTime(this._sceneT * 1000);
    if (this._nwN++ % 15 === 0) {
      const W = gl.clientWidth;
      const H = gl.clientHeight;
      if (W > 40 && H > 40) {
        const sf = this.measureSafe(gl, W, H);
        v.setInsets({ insetLeft: sf.l, insetRight: W - sf.r, insetTop: sf.t, insetBottom: H - sf.b, legendX: sf.l + 24, legendY: sf.t + 24 });
      }
    }
  }
`;
const a = s.indexOf('  draw(dt) {\n');
const a2 = s.indexOf('  draw() {\n    if (typeof document === \'undefined\' || typeof document.getElementById');
const start = a >= 0 ? a : a2;
must(start >= 0, 'draw() not found');
const end = s.indexOf('\n  }\n', start) + 5;
s = s.slice(0, start) + DRAW + s.slice(end);

fs.writeFileSync(FILE, s);
console.log('Main.dc.html:', s.length, 'bytes');
