#!/usr/bin/env node
// build-engine.mjs — (re)assemble the 3D engine region of project/Main.dc.html from tools/engine/*.js
// usage: node tools/build-engine.mjs [Main.dc.html]   (default project/Main.dc.html)
import fs from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const E = (f) => fs.readFileSync(path.join(ROOT, 'tools/engine', f), 'utf8');
const target = process.argv[2] ? path.resolve(process.argv[2]) : path.join(ROOT, 'project/Main.dc.html');
let main = fs.readFileSync(target, 'utf8');

const rep = (s, a, b) => { if (!s.includes(a)) throw new Error('engine patch anchor missing: ' + a.slice(0, 80)); return s.replace(a, b); };

let head = E('old/head.js').replace(/\n\/\/ deterministic 3D force layout[^\n]*\n$/, '\n');
let syn = E('old/synapses.js');
syn = rep(syn, '  let edgeCount = 0;\n', '');
syn = rep(syn, '    edgeCount++;\n', '');
syn = rep(syn, '  m.stats = { edges: edgeCount, nodes: 0 };\n', '');
syn = rep(syn, `    for (let s = 0; s < e.n; s++) {
      const p = proj(e.pts[s * 3], e.pts[s * 3 + 1], e.pts[s * 3 + 2]);
      e.sx[s] = p[0]; e.sy[s] = p[1];
      if (s === mid) { e.zc = p[3]; e.km = p[2]; }
    }
    e.up = upto; e.g = g;
    list.push(e);`, `    let near = false;
    for (let s = 0; s < e.n; s++) {
      const p = proj(e.pts[s * 3], e.pts[s * 3 + 1], e.pts[s * 3 + 2]);
      e.sx[s] = p[0]; e.sy[s] = p[1];
      if (p[3] < NEAR) near = true;
      if (s === mid) { e.zc = p[3]; e.km = p[2]; }
    }
    if (near) continue;
    e.up = upto; e.g = g;
    list.push(e);`);
syn = rep(syn, '(e.zc - (dist - 120)) / 260', '(e.zc - (dist - 170)) / 360');
let neu = E('old/neurons.js');
neu = rep(neu, `    nodePos(m, n, t, TMP3);
    const p = proj(TMP3[0], TMP3[1], TMP3[2]);`, `    const o3 = n.i * 3;
    TMP3[0] = m.P[o3]; TMP3[1] = m.P[o3 + 1]; TMP3[2] = m.P[o3 + 2];
    const p = proj(TMP3[0], TMP3[1], TMP3[2]);
    if (p[3] < NEAR) continue;`);
neu = rep(neu, '  m.stats.nodes = vn.length;\n', '');
neu = rep(neu, '(v.z - (dist - 120)) / 240', '(v.z - (dist - 170)) / 330');
let cards = E('old/cards.js');
cards = rep(cards, 'S.cards !== false && ', '');
let render = E('render.js');
if (render.includes('/*@@OLD:sky*/')) render = render.replace('/*@@OLD:sky*/', E('old/sky.js').replace(/\s+$/, ''));
if (render.includes('/*@@OLD:synapses*/')) render = render.replace('/*@@OLD:synapses*/', syn.replace(/\s+$/, ''));
if (render.includes('/*@@OLD:neurons*/')) render = render.replace('/*@@OLD:neurons*/', neu.replace(/\s+$/, ''));
if (render.includes('/*@@OLD:fx*/')) render = render.replace('/*@@OLD:fx*/', E('old/fx.js').replace(/\s+$/, ''));
if (render.includes('/*@@OLD:cards*/')) render = render.replace('/*@@OLD:cards*/', cards.replace(/\s+$/, ''));

const engine = '// @@ENGINE-BEGIN (generated by tools/build-engine.mjs from tools/engine/*; stage modules are delimited by @@MODULE markers)\n' + head.replace(/\s+$/, '') + '\n\n' + E('model.js').replace(/\s+$/, '') + '\n\n' + E('old/helpers.js').replace(/\s+$/, '') + '\n\n' + render.replace(/\s+$/, '') + '\n// @@ENGINE-END\n\n';
const a = main.indexOf('// @@ENGINE-BEGIN') >= 0 ? main.indexOf('// @@ENGINE-BEGIN') : main.indexOf('// ====================================================================== 3D NEURAL SPACE: scene model');
const b = main.indexOf('class Component extends DCLogic');
if (a < 0 || b < 0 || b < a) throw new Error('engine region markers not found');
main = main.slice(0, a) + engine + main.slice(b);
fs.writeFileSync(target, main);
console.log('engine rebuilt:', engine.length, 'bytes ->', target);
